from __future__ import annotations
from abc import ABC,abstractmethod
from typing import Any
from arbitrage_terminal.domain.models import Market,Ticker
class ExchangeError(RuntimeError):
    def __init__(self,message,error_type='exchange_error',http_status=None): self.error_type=error_type; self.http_status=http_status; super().__init__(message)
class ExchangeAdapter(ABC):
    name:str
    @abstractmethod
    async def health_check(self): ...
    @abstractmethod
    async def get_markets(self)->list[Market]: ...
    @abstractmethod
    async def get_tickers(self,symbols:set[str]|None=None)->list[Ticker]: ...
    @abstractmethod
    async def get_orderbook(self,symbol:str,limit:int=10)->dict[str,Any]: ...
    @abstractmethod
    async def get_trading_fees(self,symbols:set[str]|None=None)->dict[str,float]: ...
    @abstractmethod
    async def get_transfer_info(self,asset:str)->dict[str,Any]: ...
    @abstractmethod
    async def close(self): ...
